#!/bin/bash

# Global constants and configuration for startup scripts.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

ENV_FILE="${PROJECT_ROOT}/.env"
ENV_EXAMPLE_FILE="${PROJECT_ROOT}/.env.example"
SCHEMA_FILE="${PROJECT_ROOT}/database/schema.sql"
DOCKER_COMPOSE_PATH="${PROJECT_ROOT}"

DOCKER_CORE_SERVICES=(timescaledb rabbitmq flower grafana)
DOCKER_WORKER_SERVICE="celery-worker"
DOCKER_MIGRATION_SERVICE="db-migrations"
DOCKER_SCHEDULER_SERVICE="scheduler"

DEFAULT_POSTGRES_USER="analyzer"
DEFAULT_POSTGRES_DB="repo_analyzer"
DEFAULT_POSTGRES_HOST="timescaledb"
DEFAULT_POSTGRES_PORT=5432

DEFAULT_RABBITMQ_USER="analyzer"
DEFAULT_RABBITMQ_HOST="rabbitmq"
DEFAULT_RABBITMQ_PORT=5672
DEFAULT_RABBITMQ_MANAGEMENT_PORT=15672

DEFAULT_LOG_LEVEL="INFO"
DEFAULT_CELERY_WORKER_CONCURRENCY=4

MAX_HEALTH_CHECK_RETRIES=30
HEALTH_CHECK_INTERVAL=2

PASSWORD_LENGTH=24

GRAFANA_PORT="${GRAFANA_PORT:-3000}"
FLOWER_PORT="${FLOWER_PORT:-5555}"
RABBITMQ_MANAGEMENT_PORT="${RABBITMQ_MANAGEMENT_PORT:-15672}"

GRAFANA_URL="http://localhost:${GRAFANA_PORT}"
FLOWER_URL="http://localhost:${FLOWER_PORT}"
RABBITMQ_MANAGEMENT_URL="http://localhost:${RABBITMQ_MANAGEMENT_PORT}"

GRAFANA_USER="admin"
GRAFANA_PASSWORD="admin"
